/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.ConsumerResponse = factory(root.KafkaRestProxy.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ConsumerResponse model module.
   * @module model/ConsumerResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ConsumerResponse</code>.
   * @alias module:model/ConsumerResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ConsumerResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConsumerResponse} obj Optional instance to populate.
   * @return {module:model/ConsumerResponse} The populated <code>ConsumerResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instance_id')) {
        obj['instance_id'] = ApiClient.convertToType(data['instance_id'], 'String');
      }
      if (data.hasOwnProperty('base_uri')) {
        obj['base_uri'] = ApiClient.convertToType(data['base_uri'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique ID for the consumer instance in this group.
   * @member {String} instance_id
   */
  exports.prototype['instance_id'] = undefined;
  /**
   * Base URI used to construct URIs for subsequent requests against this consumer instance. This will be of the form http://hostname:port/consumers/consumer_group/instances/instance_id.
   * @member {String} base_uri
   */
  exports.prototype['base_uri'] = undefined;



  return exports;
}));


