/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Offset'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Offset'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.OffsetWithAvroSchema = factory(root.KafkaRestProxy.ApiClient, root.KafkaRestProxy.Offset);
  }
}(this, function(ApiClient, Offset) {
  'use strict';




  /**
   * The OffsetWithAvroSchema model module.
   * @module model/OffsetWithAvroSchema
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OffsetWithAvroSchema</code>.
   * @alias module:model/OffsetWithAvroSchema
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>OffsetWithAvroSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OffsetWithAvroSchema} obj Optional instance to populate.
   * @return {module:model/OffsetWithAvroSchema} The populated <code>OffsetWithAvroSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key_schema_id')) {
        obj['key_schema_id'] = ApiClient.convertToType(data['key_schema_id'], 'Number');
      }
      if (data.hasOwnProperty('value_schema_id')) {
        obj['value_schema_id'] = ApiClient.convertToType(data['value_schema_id'], 'Number');
      }
      if (data.hasOwnProperty('offsets')) {
        obj['offsets'] = ApiClient.convertToType(data['offsets'], [Offset]);
      }
    }
    return obj;
  }

  /**
   * ID returned by a previous request using the same schema. This ID corresponds to the ID of the schema in the registry.
   * @member {Number} key_schema_id
   */
  exports.prototype['key_schema_id'] = undefined;
  /**
   * ID returned by a previous request using the same schema. This ID corresponds to the ID of the schema in the registry.
   * @member {Number} value_schema_id
   */
  exports.prototype['value_schema_id'] = undefined;
  /**
   * @member {Array.<module:model/Offset>} offsets
   */
  exports.prototype['offsets'] = undefined;



  return exports;
}));


