/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.Offset = factory(root.KafkaRestProxy.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Offset model module.
   * @module model/Offset
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Offset</code>.
   * @alias module:model/Offset
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Offset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Offset} obj Optional instance to populate.
   * @return {module:model/Offset} The populated <code>Offset</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('partition')) {
        obj['partition'] = ApiClient.convertToType(data['partition'], 'Number');
      }
      if (data.hasOwnProperty('offset')) {
        obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
      }
      if (data.hasOwnProperty('error_code')) {
        obj['error_code'] = ApiClient.convertToType(data['error_code'], 'Number');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
    }
    return obj;
  }

  /**
   * Partition the message was published to, or null if publishing the message failed
   * @member {Number} partition
   */
  exports.prototype['partition'] = undefined;
  /**
   * Offset of the message, or null if publishing the message failed
   * @member {Number} offset
   */
  exports.prototype['offset'] = undefined;
  /**
   * An error code classifying the reason this operation failed, or null if it succeeded.
   * @member {Number} error_code
   */
  exports.prototype['error_code'] = undefined;
  /**
   * An error message describing why the operation failed, or null if it succeeded
   * @member {String} error
   */
  exports.prototype['error'] = undefined;



  return exports;
}));


