/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Record'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Record'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.ProduceMessages = factory(root.KafkaRestProxy.ApiClient, root.KafkaRestProxy.Record);
  }
}(this, function(ApiClient, Record) {
  'use strict';




  /**
   * The ProduceMessages model module.
   * @module model/ProduceMessages
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProduceMessages</code>.
   * @alias module:model/ProduceMessages
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ProduceMessages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProduceMessages} obj Optional instance to populate.
   * @return {module:model/ProduceMessages} The populated <code>ProduceMessages</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('records')) {
        obj['records'] = ApiClient.convertToType(data['records'], [Record]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Record>} records
   */
  exports.prototype['records'] = undefined;



  return exports;
}));


