/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.Replica = factory(root.KafkaRestProxy.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Replica model module.
   * @module model/Replica
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Replica</code>.
   * @alias module:model/Replica
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Replica</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Replica} obj Optional instance to populate.
   * @return {module:model/Replica} The populated <code>Replica</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('broker')) {
        obj['broker'] = ApiClient.convertToType(data['broker'], 'Number');
      }
      if (data.hasOwnProperty('leader')) {
        obj['leader'] = ApiClient.convertToType(data['leader'], 'Boolean');
      }
      if (data.hasOwnProperty('sync')) {
        obj['sync'] = ApiClient.convertToType(data['sync'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * broker ID of the replica
   * @member {Number} broker
   */
  exports.prototype['broker'] = undefined;
  /**
   * true if this replica is the leader for the partition
   * @member {Boolean} leader
   */
  exports.prototype['leader'] = undefined;
  /**
   * true if this replica is currently in sync with the leader
   * @member {Boolean} sync
   */
  exports.prototype['sync'] = undefined;



  return exports;
}));


