/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Topics'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Topics'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.TopicSubscriptionRequest = factory(root.KafkaRestProxy.ApiClient, root.KafkaRestProxy.Topics);
  }
}(this, function(ApiClient, Topics) {
  'use strict';




  /**
   * The TopicSubscriptionRequest model module.
   * @module model/TopicSubscriptionRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TopicSubscriptionRequest</code>.
   * @alias module:model/TopicSubscriptionRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TopicSubscriptionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopicSubscriptionRequest} obj Optional instance to populate.
   * @return {module:model/TopicSubscriptionRequest} The populated <code>TopicSubscriptionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('topics')) {
        obj['topics'] = Topics.constructFromObject(data['topics']);
      }
      if (data.hasOwnProperty('topic_pattern')) {
        obj['topic_pattern'] = ApiClient.convertToType(data['topic_pattern'], 'String');
      }
    }
    return obj;
  }

  /**
   * A list of topics to subscribe
   * @member {module:model/Topics} topics
   */
  exports.prototype['topics'] = undefined;
  /**
   * A REGEX pattern. topics_pattern and topics fields are mutually exclusive.
   * @member {String} topic_pattern
   */
  exports.prototype['topic_pattern'] = undefined;



  return exports;
}));


