/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Partition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Partition'));
  } else {
    // Browser globals (root is window)
    if (!root.KafkaRestProxy) {
      root.KafkaRestProxy = {};
    }
    root.KafkaRestProxy.Topic = factory(root.KafkaRestProxy.ApiClient, root.KafkaRestProxy.Partition);
  }
}(this, function(ApiClient, Partition) {
  'use strict';




  /**
   * The Topic model module.
   * @module model/Topic
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Topic</code>.
   * The topics resource provides information about the topics in your Kafka cluster and their current state
   * @alias module:model/Topic
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Topic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Topic} obj Optional instance to populate.
   * @return {module:model/Topic} The populated <code>Topic</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('configs')) {
        obj['configs'] = ApiClient.convertToType(data['configs'], 'String');
      }
      if (data.hasOwnProperty('partitions')) {
        obj['partitions'] = ApiClient.convertToType(data['partitions'], [Partition]);
      }
    }
    return obj;
  }

  /**
   * Name of the topic
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Per-topic configuration overrides
   * @member {String} configs
   */
  exports.prototype['configs'] = undefined;
  /**
   * List of partitions for this topic
   * @member {Array.<module:model/Partition>} partitions
   */
  exports.prototype['partitions'] = undefined;



  return exports;
}));


