/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The partitions resource provides per-partition metadata, including the current leaders and replicas for each partition
 */
export interface Partition {
    /**
     * ID of the partition
     */
    partition?: number;

    /**
     * Broker ID of the leader for this partition
     */
    leader?: number;

    /**
     * List of brokers acting as replicas for this partition
     */
    replicas?: Array<models.Replica>;

}
