export const environment = {
  production: true,
  generalErr: 'Internal error',
  result: 'Realtimesubscriptionresponse1',
  rsr: 'Realtimesubscriptionrequest1',
  pump: 'Realtimemeasurespumpuprequest1',
  kafka_rest_proxy: 'http://10.134.44.202:8082',
  AGENTMEASURES: 'AGENTMEASURES',
  AGENTBYACCOUNTMEASURES: 'AGENTBYACCOUNTMEASURES',
  ROUTINGSERVICEMEASURES: 'ROUTINGSERVICEMEASURES',
  AGENTBYROUTINGSERVICEMEASURES: 'AGENTBYROUTINGSERVICEMEASURES',
  AGENTMEASURESMOVINGWINDOW: 'AGENTMEASURESMOVINGWINDOW',
  AGENTBYACCOUNTMEASURSMOVINGWINDOW: 'AGENTBYACCOUNTMEASURSMOVINGWINDOW',
  ROUTINGSERVICEMEASURESMOVINGWINDOW: 'ROUTINGSERVICEMEASURESMOVINGWINDOW',
  AGENTBYROUTINGSERVICEMEASURESMOVINGWINDOW: 'AGENTBYROUTINGSERVICEMEASURESMOVINGWINDOW'
};
