export const environment = {
  production: true,
  server: 'http://192.168.104.18:8082', // 192.168.104.18 //11.11.254.102
  generalErr: 'Internal error',
  result: 'Realtimesubscriptionresponse',
  rsr: 'Realtimesubscriptionrequest',
  pump: 'Realtimemeasurespumpuprequest',
  AGENTMEASURES: 'AGENTMEASURES4',
  AGENTBYACCOUNTMEASURES: 'AGENTBYACCOUNTMEASURES4',
  ROUTINGSERVICEMEASURES: 'ROUTINGSERVICEMEASURES4',
  AGENTBYROUTINGSERVICEMEASURES: 'AGENTBYROUTINGSERVICEMEASURES',
  AGENTMEASURESMOVINGWINDOW: 'AGENTMEASURESMOVINGWINDOW',
  AGENTBYACCOUNTMEASURSMOVINGWINDOW: 'AGENTBYACCOUNTMEASURSMOVINGWINDOW',
  ROUTINGSERVICEMEASURESMOVINGWINDOW: 'ROUTINGSERVICEMEASURESMOVINGWINDOW',
  AGENTBYROUTINGSERVICEMEASURESMOVINGWINDOW: 'AGENTBYROUTINGSERVICEMEASURESMOVINGWINDOW'
};
