/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Offset {
    /**
     * Partition the message was published to, or null if publishing the message failed
     */
    partition?: number;

    /**
     * Offset of the message, or null if publishing the message failed
     */
    offset?: number;

    /**
     * An error code classifying the reason this operation failed, or null if it succeeded.
     */
    errorCode?: number;

    /**
     * An error message describing why the operation failed, or null if it succeeded
     */
    error?: string;

}
