/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface OffsetWithAvroSchema {
    /**
     * ID returned by a previous request using the same schema. This ID corresponds to the ID of the schema in the registry.
     */
    keySchemaId?: number;

    /**
     * ID returned by a previous request using the same schema. This ID corresponds to the ID of the schema in the registry.
     */
    valueSchemaId?: number;

    offsets?: Array<models.Offset>;

}
