/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Replica {
    /**
     * broker ID of the replica
     */
    broker?: number;

    /**
     * true if this replica is the leader for the partition
     */
    leader?: boolean;

    /**
     * true if this replica is currently in sync with the leader
     */
    sync?: boolean;

}
