/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The topics resource provides information about the topics in your Kafka cluster and their current state
 */
export interface Topic {
    /**
     * Name of the topic
     */
    name?: string;

    /**
     * Per-topic configuration overrides
     */
    configs?: string;

    /**
     * List of partitions for this topic
     */
    partitions?: Array<models.Partition>;

}
