/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TopicSubscriptionRequest {
    /**
     * A list of topics to subscribe
     */
    topics?: models.Topics;

    /**
     * A REGEX pattern. topics_pattern and topics fields are mutually exclusive.
     */
    topicPattern?: string;

}
