/**
 * Kafka REST proxy
 * Confluent Kafka REST proxy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KafkaRestProxy);
  }
}(this, function(expect, KafkaRestProxy) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KafkaRestProxy.Replica();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Replica', function() {
    it('should create an instance of Replica', function() {
      // uncomment below and update the code to test Replica
      //var instane = new KafkaRestProxy.Replica();
      //expect(instance).to.be.a(KafkaRestProxy.Replica);
    });

    it('should have the property broker (base name: "broker")', function() {
      // uncomment below and update the code to test the property broker
      //var instane = new KafkaRestProxy.Replica();
      //expect(instance).to.be();
    });

    it('should have the property leader (base name: "leader")', function() {
      // uncomment below and update the code to test the property leader
      //var instane = new KafkaRestProxy.Replica();
      //expect(instance).to.be();
    });

    it('should have the property sync (base name: "sync")', function() {
      // uncomment below and update the code to test the property sync
      //var instane = new KafkaRestProxy.Replica();
      //expect(instance).to.be();
    });

  });

}));
