export class MovingWindowAgent {
	First_Name: string;
	Last_Name: string;
	Agent_ID: number;
	Display_Name: string;
	Supervisor_First_Name: string;
	Supervisor_Last_Name: string;
	Supervisor_ID: number;
	Account_ID: number;
	Offered: number;
	Abandoned : number;
	Answered : number;
	Completed: number;
	Transfers : number;
	Conferences : number;
	Consults : number;
	Not_Answered : number;
	Holds : number;
	Active_Time : number;
	Hold_Time : number;
	Alert_Time : number;
	Not_Ready_Time : number;
	Logged_In_Time : number;
	Idle_Time : number;
	Ready: number;
	Not_Ready: number;
	Disconnects_From_Hold : number;
	Long_Holds: number;
	Last_State_Change_Time: number;
	Provider_ID: number;
	Agent_State: string;
	Work_State: string;
	ID: number;
	LastState_Change_Timestamp: number;
	Login_TimeStamp: number;
	logoutTimeStamp: number;
	NR_Reason_Code_Name: string;
	LastStateReasonTimestamp: number;
	NR_Reason_Code: string;
	Long_Engagements: number;
	Short_Engagements: number;
	Long_Wrap_Ups: number;
	Short_Wrap_Ups: number;
	Short_Not_Ready: number;
	Blended_active_time: string;
	Blended_alerting_time: string;
	Additional_time: string;
	TRANSFERRED_TO_AGENT: number;
	TRANSFERRED_TO_SERVICE: number;
	ADHOC: number;
	ADHOC_DURATION : number;
	CONSULTS_INITIATED: number;
	TRANSFERRED_INITIATED: number;
	CONFERENCED_INITIATED: number;
	CONSULTS_ACCEPTED: number;
	TRANSFERRED_ACCEPTED: number;
	CONFERENCED_ACCEPTED: number;
	TRANSFERRED_INITIATED_TO_SERVICE: number;
	TRANSFERRED_INITIATED_TO_AGENT: number;
	TRANSFERRED_ACCEPTED_FROM_SERVICE: number;
	TRANSFERRED_ACCEPTED_FROM_AGENT: number;
	COACHED: number;
	COACHING: number;
	OBSERVED: number;
	OBSERVING: number;
	BARGED_IN: number;
	BARGED_OUT: number;
	CONSULT_DURATION: number;
	CONSULTING_DURATION: number;
	CONSULTED_DURATION: number;
	COACHED_DURATION: number;
	COACHING_DURATION: number;
	OBSERVED_DURATION: number;
	OBSERVING_DURATION: number;
	BARGED_IN_DURATION: number;
	BARGED_OUT_DURATION: number;
	ACW_DURATION: number;
	ACW: number;
	ACW_EXTENDED: number;
}
