export class MovingWindowAgentByAccount {
	Agent_ID: number;
	Provider_ID: number;
	Supervisor_ID: number;
	Account_ID: number;
	Offered: number;
	Completed: number;
	Abandoned : number;
	Not_Answered : number;
	Conferences : number;
	Answered : number;
	Consults : number;
	Transfers : number;
	Hold_Time : number;
	Alert_Time : number;
	Active_Time : number;
	Not_Ready_Time : number;
	Disconnects_From_Hold : number;
	Long_Holds: number;
	ID: number;
	First_Name: string;
	Last_Name: string;
	Display_Name: string;
	Supervisor_First_Name: string;
	Supervisor_Last_Name: string;
	Ready: number;
	Not_Ready: number;
	Work_State: string;
	Channel: string;
	loginTimeStamp: string;
	logoutTimeStamp: string;
	lastStateChangeTimestamp: number;
	LastStateReasonTimestamp: number;
	agentbyAccountState: string;
	Long_Engagements: number;
	Short_Engagements: number;
	Long_Wrap_Ups: number;
	Short_Wrap_Ups: number;
	Holds : number;
	NR_Reason_Code: string;
	NR_Reason_Code_Name: string;
	Blended_Active_Time: string;
	ADHOC: number;
	ADHOC_DURATION : number;
	TRANSFERRED_TO_AGENT: number;
	TRANSFERRED_TO_SERVICE: number;
	CONSULTS_INITIATED: number;
	TRANSFERRED_INITIATED: number;
	CONFERENCED_INITIATED: number;
	CONSULTS_ACCEPTED: number;
	TRANSFERRED_ACCEPTED: number;
	CONFERENCED_ACCEPTED: number;
	TRANSFERRED_INITIATED_TO_SERVICE: number;
	TRANSFERRED_INITIATED_TO_AGENT: number;
	TRANSFERRED_ACCEPTED_FROM_SERVICE: number;
	TRANSFERRED_ACCEPTED_FROM_AGENT: number;
	COACHED: number;
	COACHING: number;
	OBSERVED: number;
	OBSERVING: number;
	BARGED_IN: number;
	BARGED_OUT: number;
	CONSULT_DURATION: number;
	CONSULTING_DURATION: number;
	COACHED_DURATION: number;
	COACHING_DURATION: number;
	OBSERVED_DURATION: number;
	OBSERVING_DURATION: number;
	BARGED_IN_DURATION: number;
	BARGED_OUT_DURATION: number;
	ACW_DURATION: number;
	ACW: number;
	ACW_EXTENDED: number;
}
