export class StartOfDayAgentByRoutingService {
	Agent_ID: number;
	Supervisor_ID: number;
	Agent_Surname: string;
	Agent_Firstname: string;
	Supervisor_Surname: string;
	Supervisor_Firstname: string;
	Service_Display_Name: string;
	Provider_ID: number;
	Channel_ID: number;
	Offered: number;
	Completed: number;
	Abandoned : number;
	Not_Answered : number;
	Conferences : number;
	Answered : number;
	Consults : number;
	Transfers : number;
	Hold_Duration : number;
	Disconnects_From_Hold : number;
	Holds : number;
	Long_Engagements: number;
	Short_Engagements: number;
	Long_Holds: number;
	TRANSFERRED_TO_AGENT: number;
	TRANSFERRED_TO_SERVICE: number;
	CONSULTS_INITIATED: number;
	TRANSFERRED_INITIATED: number;
	CONFERENCED_INITIATED: number;
	CONSULTS_ACCEPTED: number;
	TRANSFERRED_ACCEPTED: number;
	CONFERENCED_ACCEPTED: number;
	TRANSFERRED_INITIATED_TO_SERVICE: number;
	TRANSFERRED_INITIATED_TO_AGENT: number;
	TRANSFERRED_ACCEPTED_FROM_SERVICE: number;
	TRANSFERRED_ACCEPTED_FROM_AGENT: number;
	COACHED: number;
	COACHING: number;
	OBSERVED: number;
	OBSERVING: number;
	BARGED_IN: number;
	BARGED_OUT: number;
	CONSULT_DURATION: number;
	CONSULTING_DURATION: number;
	COACHED_DURATION: number;
	COACHING_DURATION: number;
	OBSERVED_DURATION: number;
	OBSERVING_DURATION: number;
	BARGED_IN_DURATION: number;
	BARGED_OUT_DURATION: number;
	ACW_DURATION: number;
	ACW: number;
	ACW_EXTENDED: number;
	Long_Wrap_Ups: number;
	Short_Wrap_Ups: number;
}
