export class StartOfDayRoutingService {
	Routing_Service_Name: string;
	Routing_Service_ID: string;
	Available: string;
	Contacts_Waiting : number;
	Contacts_At_Agent : number;
	In_ACW : number;
	Active : number;
	Answered : number;
	Answered_After_Threshold : number;
	Abandoned_After_Threshold : number;
	Held_Contacts : number;
	Holds : number;
	Alerting : number;
	Offered : number;
	Not_Answered : number;
	Abandoned : number;
	Consults : number;
	Transfers : number;
	Conferences : number;
	Hold_Time : number;
	Abandon_Time : number;
	Total_Time : number;
	Ring_Time : number;
	WaitTime : number;
	Active_Time : number;
	Oldest_Contact_Waiting : string;
	Service_Display_Name : string;
	Provider_ID : number;
	Expected_Wait_Time : number;
	Channel_ID : number;
	TRANSFERRED_TO_AGENT: number;
	TRANSFERRED_TO_SERVICE: number;
	CONSULTS_INITIATED: number;
	TRANSFERRED_INITIATED: number;
	CONFERENCED_INITIATED: number;
	CONSULTS_ACCEPTED: number;
	TRANSFERRED_ACCEPTED: number;
	CONFERENCED_ACCEPTED: number;
	TRANSFERRED_INITIATED_TO_SERVICE: number;
	TRANSFERRED_INITIATED_TO_AGENT: number;
	TRANSFERRED_ACCEPTED_FROM_SERVICE: number;
	TRANSFERRED_ACCEPTED_FROM_AGENT: number;
	COACHED: number;
	COACHING: number;
	OBSERVED: number;
	OBSERVING: number;
	BARGED_IN: number;
	BARGED_OUT: number;
	CONSULT_DURATION: number;
	CONSULTING_DURATION: number;
	COACHED_DURATION: number;
	COACHING_DURATION: number;
	OBSERVED_DURATION: number;
	OBSERVING_DURATION: number;
	BARGED_IN_DURATION: number;
	BARGED_OUT_DURATION: number;
	ACW_DURATION: number;
	ACW: number;
	ACW_EXTENDED: number;
	Long_Engagements: number;
	Short_Engagements: number;
	Long_Wrap_Ups: number;
	Short_Wrap_Ups: number;
}
