/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.BrokerApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * Confluent Kafka REST proxy
 * Version: 1.0.0
 * Generated by: io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
 */
/**
 * @license Apache 2.0
 * http://www.apache.org/licenses/LICENSE-2.0.html
 */

goog.provide('API.Client.BrokerApi');


/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.BrokerApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('BrokerApiBasePath') ?
                   /** @type {!string} */ ($injector.get('BrokerApiBasePath')) :
                   'http://11.11.254.102:8082/';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('BrokerApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('BrokerApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.BrokerApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * 
 * Get a list of brokers.
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.BrokerApi.prototype.getIDs = function(opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/brokers';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
